/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

public class App {

    public static void main(String[] args) {

    }
}

//TESTS
//PROJECT TESTS
//        ProjectController projectController = new ProjectController();
//
//        Project project = new Project();
//        project.setName("Projeto teste");
//        project.setDescription("description");
//        //Testando método save do controller
//        projectController.save(project);
//        ProjectController projectController = new ProjectController();;
//
//        Project project = new Project();
//
//        project.setId(1);
//        project.setName("Novo nome do projeto");
//        project.setDescription("description");
//        
//        //Testando método update do controller
//        projectController.update(project);
//        ProjectController projectController = new ProjectController();;
//        List<Project> projects = projectController.getAll();
//        System.out.println("total de projetos " + projects.size());
//        projectController.removeById(1);
//TASK TESTS       
//        TaskController taskController = new TaskController();
//
//        Task task = new Task();
//        task.setIdProject(2);
//        task.setName("test task");
//        task.setDescription("description");
//        task.setIsCompleted(false);
//        task.setNotes("notes");
//        task.setDeadline(new java.util.Date());
//
//        taskController.save(task);
//
//        task.setId(10);
//        task.setIdProject(2);
//        task.setDeadline(new java.util.Date());
//        task.setName("teste novo nome");
//        taskController.update(task);
//
//        List<Task> tasks = taskController.getAll(2);
//        System.out.println("total de tasks " + tasks.size());
//
//        taskController.removeById(9);
